[workspace]
release_always = false
changelog_update = false
git_tag_enable = false
git_release_enable = false

[[package]]
name = "specdrs"
changelog_update = true
changelog_include = ["specdrs-macros", "specdrs-syntax"]
git_tag_enable = true
git_tag_name = "v{{ version }}"
git_release_enable = true

[[package]]
name = "payments"
release = false
